#Node port
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  type: NodePort
  selector:
    app: my-app   # Must match deployment label
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 80    # Container port
      nodePort: 30007   # External port (optional)
      
#Create ClusterIP Service YAML
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
spec:
  type: ClusterIP   # optional (default)
  selector:
    app: my-app     # must match deployment label
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 80    # Container port

#Instead of YAML, you can create it quickly via command

kubectl expose deployment my-app-deployment \
  --type=ClusterIP \
  --port=80 \
  --target-port=80 \
  --name=my-clusterip-service
  
#Load balancer
 apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080 
